# Nom du Workflow qui apparaîtra dans l'onglet "Actions" de GitHub
name: Deploy to Firebase Hosting

# Déclencheur : ce workflow s'exécute à chaque 'push' sur la branche 'main'
on:
  push:
    branches:
      - main # ou master selon le nom de votre branche principale

# Tâches à exécuter
jobs:
  build_and_deploy:
    # Utilise la dernière version d'Ubuntu comme environnement
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Récupère le code de votre dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2: Installe Node.js, puis les dépendances du projet
      - name: Install dependencies
        # MODIFICATION ICI: on utilise "npm install" qui fonctionne sans package-lock.json
        run: npm install

      # Étape 3: Construit l'application React pour la production
      # Le résultat sera dans un dossier /dist
      - name: Build project
        run: npm run build

      # Étape 4: Déploie le contenu du dossier /dist sur Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AOD_TRACKER_OS }}'
          channelId: live
          projectId: bougienicole
